// Code generated by MockGen. DO NOT EDIT.
// Source: internal/catalog/service/category_type.go
//
// Generated by this command:
//
//	mockgen -source=internal/catalog/service/category_type.go -destination=internal/catalog/service/mock/mock_category_type.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	domain "github.com/hexley21/fixup/internal/catalog/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCategoryType is a mock of CategoryType interface.
type MockCategoryType struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryTypeMockRecorder
}

// MockCategoryTypeMockRecorder is the mock recorder for MockCategoryType.
type MockCategoryTypeMockRecorder struct {
	mock *MockCategoryType
}

// NewMockCategoryType creates a new mock instance.
func NewMockCategoryType(ctrl *gomock.Controller) *MockCategoryType {
	mock := &MockCategoryType{ctrl: ctrl}
	mock.recorder = &MockCategoryTypeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryType) EXPECT() *MockCategoryTypeMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCategoryType) Create(ctx context.Context, name string) (domain.CategoryType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(domain.CategoryType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCategoryTypeMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCategoryType)(nil).Create), ctx, name)
}

// Delete mocks base method.
func (m *MockCategoryType) Delete(ctx context.Context, id int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCategoryTypeMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCategoryType)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockCategoryType) Get(ctx context.Context, id int32) (domain.CategoryType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domain.CategoryType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCategoryTypeMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCategoryType)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockCategoryType) List(ctx context.Context, limit, offset int64) ([]domain.CategoryType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit, offset)
	ret0, _ := ret[0].([]domain.CategoryType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCategoryTypeMockRecorder) List(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCategoryType)(nil).List), ctx, limit, offset)
}

// Update mocks base method.
func (m *MockCategoryType) Update(ctx context.Context, id int32, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCategoryTypeMockRecorder) Update(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCategoryType)(nil).Update), ctx, id, name)
}
