FROM alpine:latest

RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY ./config/chat.config.yml ./config/config.yml
COPY ./bin/chat ./app
COPY ./.env ./.env
COPY ./keys/cdn/private_key.pem ./keys/cdn/private_key.pem

CMD ["./app"]