FROM alpine:latest

RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY ./config/user.config.yml ./config/config.yml
COPY ./templates/auth ./templates
COPY ./bin/user ./app
COPY ./.env ./.env
COPY ./keys/cdn/private_key.pem ./keys/cdn/private_key.pem

CMD ["./app"]