DROP TYPE CAPITAL_TYPE;
DROP TYPE ORDER_STATUS;

DROP TABLE currencies CASCADE;
DROP TABLE cities CASCADE;
DROP TABLE orders CASCADE;
DROP TABLE provider_locations CASCADE;
DROP TABLE offers CASCADE;
DROP TABLE jobs CASCADE;
DROP TABLE reviews CASCADE;
