server:
    http_port: 80
    instance_id: 1
    shutdown_timeout: 10s

postgres:
    port: 5432
    host: chat-db
    db_name: chat
    max-connections: 50
    min-connections: 10
    max-conn-lifetime: 180s
    max-conn-idle-time: 60s
    healthcheck-period: 60s

redis:
    port: 6379
    host: db
    db_name: 0
    dial_timeout: 30s

jwt:
    access_ttl: 2h
    refresh_ttl: 168h

argon2:
    salt_len: 16
    key_len: 79
    time: 3
    memory: 65536
    threads: 4

logging:
    level: debug
    caller_enabled: true
    log_file: chat.log