---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
- job_name: user-service
  static_configs:
  - targets: ["user-service:80"]
- job_name: catalog-service
  static_configs:
  - targets: ["catalog-service:80"]