server:
    instance_id: 1
    shutdown_timeout: 10s
    email: auth@fixup.com

http:
    port: 80
    cors_origins: https://localhost:5173,http://localhost:5173,https://localhost:8081,http://localhost:8081
    idle_timeout: 60s
    read_timeout: 10s
    write_timeout: 30s

postgres:
    port: 5432
    host: user-db
    db_name: user
    max-connections: 50
    min-connections: 10
    max-conn-lifetime: 180s
    max-conn-idle-time: 60s
    healthcheck-period: 60s

redis:
    addresses: redis01:6379,redis02:6379,redis03:6379,redis04:6379,redis05:6379,redis06:6379
    min_idle_conn: 30
    pool_size: 500
    read_timeout: 0.5s
    write_timeout: 0.5s
    pool_timeout: 5s

aws:
    awscfg:
        region: eu-north-1
    s3:
        bucket: fixup.com
        random_name_size: 32
    cdn:
        url_fmt: https://d20eri1dy5h30b.cloudfront.net/%s
        expiry: 24h

jwt:
    access_ttl: 2h
    refresh_ttl: 168h
    verification_ttl: 168h

argon2:
    salt_len: 16
    key_len: 79
    time: 3
    memory: 65536
    threads: 4

logging:
    level: debug
    caller_enabled: true
    log_file: user.log
