server:
    http_port: 80
    instance_id: 1
    shutdown_timeout: 10s

postgres:
    port: 5432
    host: user-db
    db_name: user
    max-connections: 50
    min-connections: 10
    max-conn-lifetime: 180s
    max-conn-idle-time: 60s
    healthcheck-period: 60s

redis:
    port: 6379
    host: db
    db_name: 0
    dial_timeout: 30s

aws: 
    awscfg:
        region: eu-north-1
    s3:
        bucket: fixup.com
        random_name_size: 32
    cdn:
        url_fmt: https://d20eri1dy5h30b.cloudfront.net/%s
        expiry: 24h


jwt:
    access_ttl: 2h
    refresh_ttl: 168h
    verification_ttl: 168h

argon2:
    salt_len: 16
    key_len: 79
    time: 3
    memory: 65536
    threads: 4

logging:
    level: debug
    caller_enabled: true
