{
 "title": "Latency & Traffic & Errors & Active Connections",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "path", "query": ".*" },
   {
    "name": "status",
    "query": "success : [2-3].*,error : [4-5].*"
   },
   { "name": "method", "query": "GET,POST,PUT,PATCH,DELETE" }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99, sum(\n        rate(\n            nginx_http_request_duration_seconds_bucket\n            {\n                path=~\"$path\",\n                status_code=~\"$status\",\n                method=~\"$method\"\n            }[1m])) by (le)\n    )",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(\n    0.90, sum(\n        rate(\n            nginx_http_request_duration_seconds_bucket\n            {\n                path=~\"$path\",\n                status_code=~\"$status\",\n                method=~\"$method\"\n            }[1m])) by (le)\n    )",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(\n    0.50, sum(\n        rate(\n            nginx_http_request_duration_seconds_bucket\n            {\n                path=~\"$path\",\n                status_code=~\"$status\",\n                method=~\"$method\"\n            }[1m])) by (le)\n    )",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(\n    sum(\n        irate(\n            nginx_http_requests_total\n            {\n                path=~\"$path\"\n            }[1m]\n            )\n        ) by (path), 0.001)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Availability (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{\n  path=~\"$path\",\n  status_code!~\"[4-5].*\"\n  }[1m])) / sum(rate(nginx_http_requests_total{path=~\"$path\"}[1m]))",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "{{ instance }}" }
   ]
  }
 ]
}