{
 "title": "user-service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "path",
    "query": "^/v1/(auth|user|profile).*,\n^/v1/auth.*,\n^/v1/users.*,\n^/v1/profile.*,\n.*,"
   },
   {
    "name": "status",
    "query": "success : [2-3].*,error : [4-5].*, All : .*"
   },
   { "name": "method", "query": "GET,POST,PUT,PATCH,DELETE" },
   { "name": "container", "query": "fixup-user-service-1" },
   { "name": "instance", "query": "user-service:8081" }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99, sum(\n        rate(\n            nginx_http_request_duration_seconds_bucket\n            {\n                path=~\"$path\",\n                status_code=~\"$status\",\n                method=~\"$method\"\n            }[1m])) by (le)\n    )",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(\n    0.90, sum(\n        rate(\n            nginx_http_request_duration_seconds_bucket\n            {\n                path=~\"$path\",\n                status_code=~\"$status\",\n                method=~\"$method\"\n            }[1m])) by (le)\n    )",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(\n    0.50, sum(\n        rate(\n            nginx_http_request_duration_seconds_bucket\n            {\n                path=~\"$path\",\n                status_code=~\"$status\",\n                method=~\"$method\"\n            }[1m])) by (le)\n    )",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=\"$container\"}[5m])) * 100",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "go_goroutines{instance=\"$instance\"}",
     "legendFormat": "GO Goroutines"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\"$container\"}[5m])) by (name)",
     "legendFormat": "Recieved"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\"$container\"}[5m])) by (name)",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(\n    sum(\n        irate(\n            nginx_http_requests_total\n            {\n                path=~\"$path\"\n            }[1m]\n            )\n        ) by (path), 0.001)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\"$container\"}) by (name)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(container_memory_cache{name=~\"$container\"}) by (name)",
     "legendFormat": "Cached"
    },
    {
     "expr": "go_memstats_alloc_bytes{instance=\"$instance\"}",
     "legendFormat": "GO Usage"
    }
   ]
  },
  {
   "title": "Availability (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{\n  path=~\"$path\",\n  status_code!~\"[4-5].*\"\n  }[1m])) / sum(rate(nginx_http_requests_total{path=~\"$path\"}[1m]))",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "{{ instance }}" }
   ]
  }
 ]
}