DROP TABLE IF EXISTS currencies CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS provider_locations CASCADE;
DROP TABLE IF EXISTS offers CASCADE;
DROP TABLE IF EXISTS jobs CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;

DROP TYPE CAPITAL_TYPE;
DROP TYPE ORDER_STATUS;