FROM golang:1.23.2-bookworm AS build

WORKDIR /app

COPY ./prometheus-nginx-exporter/go.mod ./
COPY ./prometheus-nginx-exporter/go.sum ./

RUN go mod download && go mod verify

COPY ./prometheus-nginx-exporter/ .

RUN go generate

RUN CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o exporter -a -ldflags="-s -w" -installsuffix cgo

FROM scratch

COPY --from=build /app/exporter /exporter

ENTRYPOINT ["/exporter"]